Repository dsgoficial/DsgTools, pull requests merged in 2018-08, with the labels that each got.

#294 Qgis3.0 migration new tools #293
  core/GeometricTools/geometryHandler.py
  gui/ProductionTools/MapTools/Acquisition/acquisition.py
  gui/ProductionTools/MapTools/Acquisition/distanceToolTip.py
  gui/ProductionTools/MapTools/Acquisition/geometricaAquisition.py
  gui/ProductionTools/MapTools/Acquisition/polygon.py
  gui/ProductionTools/MapTools/Acquisition/toolTip.py
  gui/ProductionTools/MapTools/FlipLineTool/flipLineTool.py
  gui/ProductionTools/MapTools/FreeHandTool/controllers/acquisitionFreeController.py
  gui/ProductionTools/MapTools/FreeHandTool/freeHandMain.py
  gui/ProductionTools/MapTools/FreeHandTool/models/acquisitionFree.py
  gui/ProductionTools/MapTools/GenericSelectionTool/genericSelectionTool.py
  gui/ProductionTools/MapTools/mapToolsGuiManager.py
  gui/ProductionTools/Toolbars/DsgRasterInfoTool/assignBandValueTool.py
  gui/ProductionTools/Toolbars/DsgRasterInfoTool/dsgRasterInfoTool.py
  gui/ProductionTools/Toolbars/DsgRasterInfoTool/dsgRasterInfoTool_ui.py
  icons/valueSetter.png
  resources.qrc
  resources_rc.py
Labels: enhancement

#299 free hand bug fixed
  gui/ProductionTools/MapTools/FreeHandTool/controllers/acquisitionFreeController.py
  gui/ProductionTools/MapTools/mapToolsGuiManager.py
Labels: bug

#302 Sugestão de alteração com Reshape
  ProductionTools/ FreeHandTool/ controllers/acquisitionFreeController.py
  ProductionTools/ FreeHandTool/ models/acquisitionFree.py
Labels: enhancement, new feature
