Repository dsgoficial/DsgTools, pull requests merged in 2019-08, with the labels that each got.

#407 toggle labels tool
  gui/ProductionTools/MapTools/FreeHandTool/freeHandMain.py
  gui/ProductionTools/MapTools/FreeHandTool/freeHandReshape.py
  gui/ProductionTools/MapTools/LabelTogglingTool/__init__.py
  gui/ProductionTools/MapTools/LabelTogglingTool/labelTogglingTool.py
  gui/ProductionTools/MapTools/mapToolsGuiManager.py
  icons/toggleActiveLayerLabel.png
  icons/toggleAllLabels.png
  icons/toggleSelectedLayersLabel.png
  resources.py
  resources.qrc
  resources_rc.py
Labels: new feature

#409 fixed reshape not working with polygons
  gui/ProductionTools/MapTools/FreeHandTool/controllers/acquisitionFreeController.py
  metadata.txt
Labels: bug

#411 Qgis3.0 migration validation algs revision
  core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyOutOfBoundsAnglesAlgorithm.py
  core/GeometricTools/geometryHandler.py
  metadata.txt
  tests/expected_outputs/identifyandfixinvalidgeometries/test_1.gpkg
  tests/expected_outputs/identifydangles/test_1.gpkg
  tests/expected_outputs/identifyduplicatedfeatures/test_1.gpkg
  tests/expected_outputs/identifyduplicatedlinesoncoverage/test_1.gpkg
  tests/expected_outputs/identifyduplicatedpointsoncoverage/test_1.gpkg
  tests/expected_outputs/identifyduplicatedpolygonsoncoverage/test_1.gpkg
  tests/expected_outputs/identifyoutofboundsangles/test_1.gpkg
  tests/expected_outputs/identifyoutofboundsanglesincoverage/test_1.gpkg
  tests/expected_outputs/identifysmalllines/test_1.gpkg
  tests/expected_outputs/identifysmallpolygons/test_1.gpkg
  tests/expected_outputs/mergelineswithsameattributeset/test_1.gpkg
Labels: bug, enhancement

#410 Qgis3.0 migration algs unit test alg
  core/DSGToolsProcessingAlgs/Algs/OtherAlgs/singleOutputUnitTestAlgorithm.py
  core/DSGToolsProcessingAlgs/dsgtoolsProcessingAlgorithmProvider.py
  core/GeometricTools/featureHandler.py
  metadata.txt
  tests/test_ValidationAlgorithms.py
Labels: enhancement, new feature
